name: 'Java CI with Maven [master]'
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          maven-version: 3.8.6
          java-version: 1.17
      - name: Build with Maven
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: mvn clean verify -ntp -B
